# Generated by Django 4.0.1 on 2022-01-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank',
            field=models.ManyToManyField(null=True, to='companies.Bank'),
        ),
    ]
