# Generated by Django 4.0.1 on 2022-01-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bank',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='comp',
            new_name='comp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='personal_data',
            new_name='personal_data_id',
        ),
    ]
