# Generated by Django 4.0.1 on 2022-01-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_comp_id_employee_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank',
            field=models.ManyToManyField(blank=True, null=True, to='companies.Bank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.personaldata'),
        ),
    ]
