class MaxLenght:
    MAX_EMPLOYEE_NAME_LENGTH = 100
    MAX_EMPLOYEE_SURENAME_LENGTH = 100
    MAX_EMPLOYEE_JOB_POSITION_LENGTH = 100
    MAX_COMPANY_NAME_LENGTH = 100
    MAX_COMPANY_WEBSITE_LENGTH = 200
    MAX_COMPANY_EMAIL_LENGTH = 100
    MAX_BANK_NAME_LENGTH = 100
    MAX_BANK_WEBSITE_LENGTH = 200
    MAX_BANK_EMAIL_LENGTH = 100
    MAX_PERSONALDATA_HOMEADRESS_LENGTH = 100