# Generated by Django 4.0.1 on 2022-01-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='comp_id',
            new_name='comp',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='personal_data_id',
            new_name='personal_data',
        ),
    ]
